export const supervisor = [
  "Dr. Adeel Anjum",
  "Dr. Adnan Akhunzada",
  "Dr. Ahmad R. Shahid",
  "Dr. Aimal Tariq Rextin",
  "Dr. Akber Abid Gardezi",
  "Dr. Amir Hanif Dar",
  "Dr. Ashfaq Hussain Farooqi",
  "Dr. Assad Abbas",
  "Dr. Basit Raza",
  "Dr. Farhana Jabeen",
  "Dr. Hasan Ali Khattak",
  "Dr. Iftikhar Azim Niaz",
  "Dr. Inayat-ur-Rehman",
  "Dr. Javed Iqbal",
  "Dr. Majid Iqbal Khan",
  "Dr. Malik Ahmad Kamran",
  "Dr. Mansoor Ahmed",
  "Dr. Mariam Akbar",
  "Dr. Masoom Alam",
  "Dr. Mubeen Ghafoor",
  "Dr. Muhammad Asim Noor",
  "Dr. Muhammad Imran",
  "Dr. Muhammad Manzoor ilahi Tamimy",
  "Dr. Muhammad Waqar",
  "Dr. Mukhtar Azeem",
  "Dr. Munam Ali Shah",
  "Dr. Nadeem Javaid",
  "Dr. Naveed Ahmad",
  "Dr. Saif ur Rehman Khan",
  "Dr. Saif Ur Rehman Malik",
  "Dr. Sajjad A. Madani",
  "Dr. Shahid Hussain",
  "Dr. Sheneela Naz",
  "Dr. Syed Sohaib Ali",
  "Dr. Tahir Mustafa Madni",
  "Dr. Tehseen Zia",
  "Dr. Usman Yaseen",
  "Dr. Uzair Iqbal",
  "Dr. Yasir Faheem",
  "Dr. Zobia Rehman",
  "Prof. Dr. Muaz A. Niazi",
  "Prof. Dr. Sohail Asghar",
];
